#!/bin/bash

IF_NAME="xfrmi-${PLUTO_UNIQUEID}"

case "${PLUTO_VERB}" in
    up-client)
        echo /usr/local/libexec/ipsec/xfrmi -n "${IF_NAME}" -i "${PLUTO_IF_ID_IN}" -d eth0
        echo /usr/local/libexec/ipsec/xfrmi -n "${IF_NAME}" -i "${PLUTO_IF_ID_OUT}" -d eth0
        /usr/local/libexec/ipsec/xfrmi -n "${IF_NAME}-in" -i "${PLUTO_IF_ID_IN}" -d eth0
        /usr/local/libexec/ipsec/xfrmi -n "${IF_NAME}-out" -i "${PLUTO_IF_ID_OUT}" -d eth0
        ip link set "${IF_NAME}-in" up
        ip link set "${IF_NAME}-out" up
        ip route add 10.1.0.0/16 dev "${IF_NAME}-out"
        iptables -A FORWARD -i "${IF_NAME}-in" -j ACCEPT
        iptables -A FORWARD -o "${IF_NAME}-out" -j ACCEPT
        ;;
    down-client)
        iptables -D FORWARD -i "${IF_NAME}-in" -j ACCEPT
        iptables -D FORWARD -o "${IF_NAME}-out" -j ACCEPT
        ip -s link show "${IF_NAME}-in"
        ip -s link show "${IF_NAME}-out"
        ip link del "${IF_NAME}-in"
        ip link del "${IF_NAME}-out"
        ;;
esac
